name: Cleanup Branches

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List branches and filter
        shell: bash
        run: |
          git fetch --prune --unshallow
          git branch -r --format="%(refname:short) %(committerdate:short)" | grep -v "HEAD" | while read branch; do
            branch_name=$(echo "$branch" | awk '{print $1}')
            last_commit_date=$(echo "$branch" | awk '{print $2}')
            if [[ $last_commit_date < "$(date -d 'yesterday' +'%Y-%m-%d')" ]]; then
              echo "$branch_name" >> AllBranches.txt
            fi
          done

      - name: Remove exceptions
        shell: bash
        run: |
          while IFS= read -r branch; do
            sed -i "/$branch/d" AllBranches.txt
          done < exceptions.txt

      - name: Delete branches
        shell: bash
        run: |
          while IFS= read -r branch; do
            git push --delete origin "$branch"
          done < AllBranches.txt
