name: Delete Old Branches

on:
  schedule:
    - cron: "0 0 * * *" # Runs every hour

jobs:
  delete_old_branches:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete old branches
        run: |
          EXCEPTION_FILE="exceptions.txt"
          OLD_BRANCHES=$(git for-each-ref --format='%(refname:short) %(committerdate:iso8601)' refs/heads/ |
                          awk -v date="$(date --date='24 hours ago' --iso-8601=seconds)" '$2 < date {print $1}')

          if [ -f "$EXCEPTION_FILE" ]; then
              EXCEPTION_BRANCHES=$(< "$EXCEPTION_FILE")
              # Filter out branches listed in exceptions.txt
              OLD_BRANCHES=$(comm -23 <(echo "$OLD_BRANCHES" | sort) <(echo "$EXCEPTION_BRANCHES" | sort))
          fi

          for branch in $OLD_BRANCHES; do
              git branch -d "$branch"
          done
