name: Cleanup Branches

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List branches and filter
        shell: bash
        run: |
          git fetch --prune --unshallow
          git branch -r --format="%(refname:short) %(committerdate:short)" | grep -v "HEAD" | ForEach-Object {
            $branch = $_ -split '\s+', 2
            $branch_name = $branch[0]
            $last_commit_date = $branch[1]
            if ($last_commit_date -lt (Get-Date).AddDays(-1).ToString("yyyy-MM-dd")) {
              Add-Content -Path "AllBranches.txt" -Value $branch_name
            }
          }

      - name: Remove exceptions
        shell: bash
        run: |
          Get-Content exceptions.txt | ForEach-Object {
            $branch = $_
            (Get-Content -Path "AllBranches.txt") -notmatch $branch | Set-Content -Path "AllBranches.txt"
          }

      - name: Delete branches
        shell: bash
        run: |
          Get-Content AllBranches.txt | ForEach-Object {
            $branch = $_
            git push --delete origin $branch
          }

      - name: Clear AllBranches.txt
        shell: bash
        run: |
          Clear-Content -Path "AllBranches.txt"
