name: Cleanup Branches

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List branches and filter
        shell: bash
        run: |
          git fetch --prune --unshallow
          git branch -r --format="%(refname:short) %(committerdate:short)" | grep -v "HEAD" | while read branch date; do
            if [[ "$date" < "$(date -d '-1 day' +%Y-%m-%d)" ]]; then
              echo "$branch" >> AllBranches.txt
            fi
          done

      - name: Remove exceptions
        shell: bash
        run: |
          while IFS= read -r branch; do
            grep -v "$branch" AllBranches.txt > tmpfile && mv tmpfile AllBranches.txt
          done < exceptions.txt

      - name: Delete branches
        shell: bash
        run: |
          while IFS= read -r branch; do
            git push --delete origin "$branch"
          done < AllBranches.txt

      - name: Clear AllBranches.txt
        shell: bash
        run: |
          > AllBranches.txt
