name: Delete inactive branches

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  delete_inactive_branches:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List branches
      run: git branch -r --format="%(committerdate:iso8601) %(refname:short)" --sort="-committerdate"

    - name: Read excluded branches from file
      id: read_excluded_branches
      run: |
        Get-Content excluded_branches.txt

    - name: Delete inactive branches
      run: |
        # Read excluded branches from the output of the previous step
        $excluded_branches = ${{ steps.read_excluded_branches.outputs.excluded_branches }} -split "`r`n"

        # Loop through branches and delete those inactive for more than 6 months
        git branch -r --format="%(committerdate:iso8601) %(refname:short)" --sort="-committerdate" | ForEach-Object {
          $branch = $_ -split " "
          $branch_name = $branch[1]
          $last_commit_date = $branch[0]
          $six_months_ago = (Get-Date).AddMonths(-6)

          # Check if the branch should be excluded from deletion
          $excluded = $false
          foreach ($excluded_branch in $excluded_branches) {
            if ($branch_name -eq $excluded_branch) {
              $excluded = $true
              break
            }
          }

          # Delete the branch if it's older than 6 months and not excluded
          if (($last_commit_date -lt $six_months_ago) -and (-not $excluded)) {
            git push origin --delete $branch_name
          }
        }
